<<<<<<< HEAD
permalink: /:year:month:day/:title
url: #Your url here
baseurl: /project

# variables
name: Your Site Name
description: Your description here
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
=======
---
title: Minimal Text
baseurl: "/"
desc: A minimal blog for off-topic blog entries.
about: test for about
image: 
excerpt_separator: "<!-- more -->"
>>>>>>> 6f594e881508d0ffb1acc9b18113b8f46276c4a9
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true