---
title: Minimal Text
baseurl: "/"
desc: A minimal blog for off-topic blog entries.
about: test for about
image: 
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
